"""
Setup configuration for customer-events pipeline.
Auto-generated by CI/CD Agent.
"""

import setuptools

REQUIRED_PACKAGES = [
    'apache-beam[gcp]==2.50.0',
]

setuptools.setup(
    name='customer-events',
    version='1.0.0',
    description='Process customer events in real time',
    install_requires=REQUIRED_PACKAGES,
    packages=setuptools.find_packages(),
    python_requires='>=3.7',
)