"""
Setup configuration for bbc-new-pipeline-42 pipeline.
Auto-generated by CI/CD Agent.
"""

import setuptools

REQUIRED_PACKAGES = [
    'apache-beam[gcp]==2.50.0',
]

setuptools.setup(
    name='bbc-new-pipeline-42',
    version='1.0.0',
    description='bbc-new-pipeline-42 pipeline',
    install_requires=REQUIRED_PACKAGES,
    packages=setuptools.find_packages(),
    python_requires='>=3.7',
)