"""
Setup configuration for austin-311-pipeline-1 pipeline.
Auto-generated by CI/CD Agent.
"""

import setuptools

REQUIRED_PACKAGES = [
    'apache-beam[gcp]==2.50.0',
]

setuptools.setup(
    name='austin-311-pipeline-1',
    version='1.0.0',
    description='austin-311-pipeline-1 pipeline',
    install_requires=REQUIRED_PACKAGES,
    packages=setuptools.find_packages(),
    python_requires='>=3.7',
)