"""
Setup configuration for bbc-news-pipeline-75 pipeline.
Auto-generated by CI/CD Agent.
"""

import setuptools

REQUIRED_PACKAGES = [
    'apache-beam[gcp]==2.50.0',
]

setuptools.setup(
    name='bbc-news-pipeline-75',
    version='1.0.0',
    description='bbc-news-pipeline-75 pipeline',
    install_requires=REQUIRED_PACKAGES,
    packages=setuptools.find_packages(),
    python_requires='>=3.7',
)