# Terraform variables for bbc-new-pipeline-42
# Auto-generated by CI/CD Agent

project_id    = "axiomatic-robot-458302-r0"
region        = "us-central1"
github_owner  = "chandanacode09"
github_repo   = "dataflow-ci-cd"
