"""
Setup configuration for autin-incidents-pipeline pipeline.
Auto-generated by CI/CD Agent.
"""

import setuptools

REQUIRED_PACKAGES = [
    'apache-beam[gcp]==2.50.0',
]

setuptools.setup(
    name='autin-incidents-pipeline',
    version='1.0.0',
    description='The pipeline for austin incidents',
    install_requires=REQUIRED_PACKAGES,
    packages=setuptools.find_packages(),
    python_requires='>=3.7',
)